language: php
php:
  - '7.0'
  - '7.1'

install:
  - composer self-update
  - composer install

script:
  - composer lint
  - composer test

after_success:
  - travis_retry composer exec 'coveralls -v'
